### ISSUE TITLE
Use new syntax for init containers

### ISSUE THREAD

**Issue by cesartl** [tarosky/k8s-redis-ha#24]
From the [documentation](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), it can be read:

>1.5 syntax still works on 1.6, but we recommend using 1.6 syntax. In Kubernetes 1.6, Init Containers were made a field in the API. The beta annotation is still respected in 1.6 and 1.7, but is not supported in 1.8 or greater.

Running K8s 1.9.0, I've had problems running `k8s-redis-ha` which uses the old notation for init containers.

I think it would be better to support the latest version of k8s, perhaps keeping the old one for legacy support
```yaml
      initContainers:
        - name: k8s-redis-ha-server
          image: tarosky/k8s-redis-ha:server-3.0.1
          volumeMounts:
            - name: opt
              mountPath: /opt
```

I'm happy to make PR if that helps
